#!/usr/bin/env python3
"""Gilgamesh, the definitive reverse engineering tool for SNES."""

import argparse

from gilgamesh.analyzer import Analyzer
from gilgamesh.database import Database
from gilgamesh.prompt import Prompt
from gilgamesh.rom import ROM


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('database', help='the database generated by the emulator')
    parser.add_argument('rom', help='the original Super Nintendo game (without header)')
    args = parser.parse_args()

    database = Database(args.database)
    rom = ROM(args.rom)
    analyzer = Analyzer(database)

    prompt = Prompt(analyzer, rom)
    prompt.run()
