from collections import namedtuple
from enum import Enum, IntEnum


class OpcodeCategory(tuple, Enum):
    BRANCH = (0x10, 0x30, 0x50, 0x70, 0x80, 0x82, 0x90, 0xB0, 0xD0, 0xF0)
    CALL = (0x20, 0x22, 0xFC)
    RETURN = (0x40, 0x60, 0x6B)
    JUMP = (0x4C, 0x5C, 0x6C, 0x7C, 0xDC)


class AddressMode(IntEnum):
    IMPLIED = 0
    IMMEDIATE_M = 1
    IMMEDIATE_X = 2
    IMMEDIATE_8 = 3
    RELATIVE = 4
    RELATIVE_LONG = 5
    DIRECT_PAGE = 6
    DIRECT_PAGE_INDEXED_X = 7
    DIRECT_PAGE_INDEXED_Y = 8
    DIRECT_PAGE_INDIRECT = 9
    DIRECT_PAGE_INDEXED_INDIRECT = 10
    DIRECT_PAGE_INDIRECT_INDEXED = 11
    DIRECT_PAGE_INDIRECT_LONG = 12
    DIRECT_PAGE_INDIRECT_INDEXED_LONG = 13
    ABSOLUTE = 14
    ABSOLUTE_INDEXED_X = 15
    ABSOLUTE_INDEXED_Y = 16
    ABSOLUTE_LONG = 17
    ABSOLUTE_INDEXED_LONG = 18
    STACK_RELATIVE = 19
    STACK_RELATIVE_INDIRECT_INDEXED = 20
    ABSOLUTE_INDIRECT = 21
    ABSOLUTE_INDIRECT_LONG = 22
    ABSOLUTE_INDEXED_INDIRECT = 23
    IMPLIED_ACCUMULATOR = 24
    MOVE = 25
    PEA = 26
    PEI_DIRECT_PAGE_INDIRECT = 27


Opcode = namedtuple('Opcode', ['number', 'mnemonic', 'address_mode'])


opcode_table = (
    Opcode(0x00, 'brk', AddressMode.IMMEDIATE_8),
    Opcode(0x01, 'ora', AddressMode.DIRECT_PAGE_INDEXED_INDIRECT),
    Opcode(0x02, 'cop', AddressMode.IMMEDIATE_8),
    Opcode(0x03, 'ora', AddressMode.STACK_RELATIVE),
    Opcode(0x04, 'tsb', AddressMode.DIRECT_PAGE),
    Opcode(0x05, 'ora', AddressMode.DIRECT_PAGE),
    Opcode(0x06, 'asl', AddressMode.DIRECT_PAGE),
    Opcode(0x07, 'ora', AddressMode.DIRECT_PAGE_INDIRECT_LONG),
    Opcode(0x08, 'php', AddressMode.IMPLIED),
    Opcode(0x09, 'ora', AddressMode.IMMEDIATE_M),
    Opcode(0x0A, 'asl', AddressMode.IMPLIED_ACCUMULATOR),
    Opcode(0x0B, 'phd', AddressMode.IMPLIED),
    Opcode(0x0C, 'tsb', AddressMode.ABSOLUTE),
    Opcode(0x0D, 'ora', AddressMode.ABSOLUTE),
    Opcode(0x0E, 'asl', AddressMode.ABSOLUTE),
    Opcode(0x0F, 'ora', AddressMode.ABSOLUTE_LONG),
    Opcode(0x10, 'bpl', AddressMode.RELATIVE),
    Opcode(0x11, 'ora', AddressMode.DIRECT_PAGE_INDIRECT_INDEXED),
    Opcode(0x12, 'ora', AddressMode.DIRECT_PAGE_INDIRECT),
    Opcode(0x13, 'ora', AddressMode.STACK_RELATIVE_INDIRECT_INDEXED),
    Opcode(0x14, 'trb', AddressMode.DIRECT_PAGE),
    Opcode(0x15, 'ora', AddressMode.DIRECT_PAGE_INDEXED_X),
    Opcode(0x16, 'asl', AddressMode.DIRECT_PAGE_INDEXED_X),
    Opcode(0x17, 'ora', AddressMode.DIRECT_PAGE_INDIRECT_INDEXED_LONG),
    Opcode(0x18, 'clc', AddressMode.IMPLIED),
    Opcode(0x19, 'ora', AddressMode.ABSOLUTE_INDEXED_Y),
    Opcode(0x1A, 'inc', AddressMode.IMPLIED_ACCUMULATOR),
    Opcode(0x1B, 'tcs', AddressMode.IMPLIED),
    Opcode(0x1C, 'trb', AddressMode.ABSOLUTE),
    Opcode(0x1D, 'ora', AddressMode.ABSOLUTE_INDEXED_X),
    Opcode(0x1E, 'asl', AddressMode.ABSOLUTE_INDEXED_X),
    Opcode(0x1F, 'ora', AddressMode.ABSOLUTE_INDEXED_LONG),
    Opcode(0x20, 'jsr', AddressMode.ABSOLUTE),
    Opcode(0x21, 'and', AddressMode.DIRECT_PAGE_INDEXED_INDIRECT),
    Opcode(0x22, 'jsl', AddressMode.ABSOLUTE_LONG),
    Opcode(0x23, 'and', AddressMode.STACK_RELATIVE),
    Opcode(0x24, 'bit', AddressMode.DIRECT_PAGE),
    Opcode(0x25, 'and', AddressMode.DIRECT_PAGE),
    Opcode(0x26, 'rol', AddressMode.DIRECT_PAGE),
    Opcode(0x27, 'and', AddressMode.DIRECT_PAGE_INDIRECT_LONG),
    Opcode(0x28, 'plp', AddressMode.IMPLIED),
    Opcode(0x29, 'and', AddressMode.IMMEDIATE_M),
    Opcode(0x2A, 'rol', AddressMode.IMPLIED_ACCUMULATOR),
    Opcode(0x2B, 'pld', AddressMode.IMPLIED),
    Opcode(0x2C, 'bit', AddressMode.ABSOLUTE),
    Opcode(0x2D, 'and', AddressMode.ABSOLUTE),
    Opcode(0x2E, 'rol', AddressMode.ABSOLUTE),
    Opcode(0x2F, 'and', AddressMode.ABSOLUTE_LONG),
    Opcode(0x30, 'bmi', AddressMode.RELATIVE),
    Opcode(0x31, 'and', AddressMode.DIRECT_PAGE_INDIRECT_INDEXED),
    Opcode(0x32, 'and', AddressMode.DIRECT_PAGE_INDIRECT),
    Opcode(0x33, 'and', AddressMode.STACK_RELATIVE_INDIRECT_INDEXED),
    Opcode(0x34, 'bit', AddressMode.DIRECT_PAGE_INDEXED_X),
    Opcode(0x35, 'and', AddressMode.DIRECT_PAGE_INDEXED_X),
    Opcode(0x36, 'rol', AddressMode.DIRECT_PAGE_INDEXED_X),
    Opcode(0x37, 'and', AddressMode.DIRECT_PAGE_INDIRECT_INDEXED_LONG),
    Opcode(0x38, 'sec', AddressMode.IMPLIED),
    Opcode(0x39, 'and', AddressMode.ABSOLUTE_INDEXED_Y),
    Opcode(0x3A, 'dec', AddressMode.IMPLIED_ACCUMULATOR),
    Opcode(0x3B, 'tsc', AddressMode.IMPLIED),
    Opcode(0x3C, 'bit', AddressMode.ABSOLUTE_INDEXED_X),
    Opcode(0x3D, 'and', AddressMode.ABSOLUTE_INDEXED_X),
    Opcode(0x3E, 'rol', AddressMode.ABSOLUTE_INDEXED_X),
    Opcode(0x3F, 'and', AddressMode.ABSOLUTE_INDEXED_LONG),
    Opcode(0x40, 'rti', AddressMode.IMPLIED),
    Opcode(0x41, 'eor', AddressMode.DIRECT_PAGE_INDEXED_INDIRECT),
    Opcode(0x42, 'wdm', AddressMode.IMMEDIATE_8),
    Opcode(0x43, 'eor', AddressMode.STACK_RELATIVE),
    Opcode(0x44, 'mvp', AddressMode.MOVE),
    Opcode(0x45, 'eor', AddressMode.DIRECT_PAGE),
    Opcode(0x46, 'lsr', AddressMode.DIRECT_PAGE),
    Opcode(0x47, 'eor', AddressMode.DIRECT_PAGE_INDIRECT_LONG),
    Opcode(0x48, 'pha', AddressMode.IMPLIED),
    Opcode(0x49, 'eor', AddressMode.IMMEDIATE_M),
    Opcode(0x4A, 'lsr', AddressMode.IMPLIED_ACCUMULATOR),
    Opcode(0x4B, 'phk', AddressMode.IMPLIED),
    Opcode(0x4C, 'jmp', AddressMode.ABSOLUTE),
    Opcode(0x4D, 'eor', AddressMode.ABSOLUTE),
    Opcode(0x4E, 'lsr', AddressMode.ABSOLUTE),
    Opcode(0x4F, 'eor', AddressMode.ABSOLUTE_LONG),
    Opcode(0x50, 'bvc', AddressMode.RELATIVE),
    Opcode(0x51, 'eor', AddressMode.DIRECT_PAGE_INDIRECT_INDEXED),
    Opcode(0x52, 'eor', AddressMode.DIRECT_PAGE_INDIRECT),
    Opcode(0x53, 'eor', AddressMode.STACK_RELATIVE_INDIRECT_INDEXED),
    Opcode(0x54, 'mvn', AddressMode.MOVE),
    Opcode(0x55, 'eor', AddressMode.DIRECT_PAGE_INDEXED_X),
    Opcode(0x56, 'lsr', AddressMode.DIRECT_PAGE_INDEXED_X),
    Opcode(0x57, 'eor', AddressMode.DIRECT_PAGE_INDIRECT_INDEXED_LONG),
    Opcode(0x58, 'cli', AddressMode.IMPLIED),
    Opcode(0x59, 'eor', AddressMode.ABSOLUTE_INDEXED_Y),
    Opcode(0x5A, 'phy', AddressMode.IMPLIED),
    Opcode(0x5B, 'tcd', AddressMode.IMPLIED),
    Opcode(0x5C, 'jmp', AddressMode.ABSOLUTE_LONG),
    Opcode(0x5D, 'eor', AddressMode.ABSOLUTE_INDEXED_X),
    Opcode(0x5E, 'lsr', AddressMode.ABSOLUTE_INDEXED_X),
    Opcode(0x5F, 'eor', AddressMode.ABSOLUTE_INDEXED_LONG),
    Opcode(0x60, 'rts', AddressMode.IMPLIED),
    Opcode(0x61, 'adc', AddressMode.DIRECT_PAGE_INDEXED_INDIRECT),
    Opcode(0x62, 'per', AddressMode.RELATIVE_LONG),
    Opcode(0x63, 'adc', AddressMode.STACK_RELATIVE),
    Opcode(0x64, 'stz', AddressMode.DIRECT_PAGE),
    Opcode(0x65, 'adc', AddressMode.DIRECT_PAGE),
    Opcode(0x66, 'ror', AddressMode.DIRECT_PAGE),
    Opcode(0x67, 'adc', AddressMode.DIRECT_PAGE_INDIRECT_LONG),
    Opcode(0x68, 'pla', AddressMode.IMPLIED),
    Opcode(0x69, 'adc', AddressMode.IMMEDIATE_M),
    Opcode(0x6A, 'ror', AddressMode.IMPLIED_ACCUMULATOR),
    Opcode(0x6B, 'rtl', AddressMode.IMPLIED),
    Opcode(0x6C, 'jmp', AddressMode.ABSOLUTE_INDIRECT),
    Opcode(0x6D, 'adc', AddressMode.ABSOLUTE),
    Opcode(0x6E, 'ror', AddressMode.ABSOLUTE),
    Opcode(0x6F, 'adc', AddressMode.ABSOLUTE_LONG),
    Opcode(0x70, 'bvs', AddressMode.RELATIVE),
    Opcode(0x71, 'adc', AddressMode.DIRECT_PAGE_INDIRECT_INDEXED),
    Opcode(0x72, 'adc', AddressMode.DIRECT_PAGE_INDIRECT),
    Opcode(0x73, 'adc', AddressMode.STACK_RELATIVE_INDIRECT_INDEXED),
    Opcode(0x74, 'stz', AddressMode.DIRECT_PAGE_INDEXED_X),
    Opcode(0x75, 'adc', AddressMode.DIRECT_PAGE_INDEXED_X),
    Opcode(0x76, 'ror', AddressMode.DIRECT_PAGE_INDEXED_X),
    Opcode(0x77, 'adc', AddressMode.DIRECT_PAGE_INDIRECT_INDEXED_LONG),
    Opcode(0x78, 'sei', AddressMode.IMPLIED),
    Opcode(0x79, 'adc', AddressMode.ABSOLUTE_INDEXED_Y),
    Opcode(0x7A, 'ply', AddressMode.IMPLIED),
    Opcode(0x7B, 'tdc', AddressMode.IMPLIED),
    Opcode(0x7C, 'jmp', AddressMode.ABSOLUTE_INDEXED_INDIRECT),
    Opcode(0x7D, 'adc', AddressMode.ABSOLUTE_INDEXED_X),
    Opcode(0x7E, 'ror', AddressMode.ABSOLUTE_INDEXED_X),
    Opcode(0x7F, 'adc', AddressMode.ABSOLUTE_INDEXED_LONG),
    Opcode(0x80, 'bra', AddressMode.RELATIVE),
    Opcode(0x81, 'sta', AddressMode.DIRECT_PAGE_INDEXED_INDIRECT),
    Opcode(0x82, 'brl', AddressMode.RELATIVE_LONG),
    Opcode(0x83, 'sta', AddressMode.STACK_RELATIVE),
    Opcode(0x84, 'sty', AddressMode.DIRECT_PAGE),
    Opcode(0x85, 'sta', AddressMode.DIRECT_PAGE),
    Opcode(0x86, 'stx', AddressMode.DIRECT_PAGE),
    Opcode(0x87, 'sta', AddressMode.DIRECT_PAGE_INDIRECT_LONG),
    Opcode(0x88, 'dey', AddressMode.IMPLIED),
    Opcode(0x89, 'bit', AddressMode.IMMEDIATE_M),
    Opcode(0x8A, 'txa', AddressMode.IMPLIED),
    Opcode(0x8B, 'phb', AddressMode.IMPLIED),
    Opcode(0x8C, 'sty', AddressMode.ABSOLUTE),
    Opcode(0x8D, 'sta', AddressMode.ABSOLUTE),
    Opcode(0x8E, 'stx', AddressMode.ABSOLUTE),
    Opcode(0x8F, 'sta', AddressMode.ABSOLUTE_LONG),
    Opcode(0x90, 'bcc', AddressMode.RELATIVE),
    Opcode(0x91, 'sta', AddressMode.DIRECT_PAGE_INDIRECT_INDEXED),
    Opcode(0x92, 'sta', AddressMode.DIRECT_PAGE_INDIRECT),
    Opcode(0x93, 'sta', AddressMode.STACK_RELATIVE_INDIRECT_INDEXED),
    Opcode(0x94, 'sty', AddressMode.DIRECT_PAGE_INDEXED_X),
    Opcode(0x95, 'sta', AddressMode.DIRECT_PAGE_INDEXED_X),
    Opcode(0x96, 'stx', AddressMode.DIRECT_PAGE_INDEXED_Y),
    Opcode(0x97, 'sta', AddressMode.DIRECT_PAGE_INDIRECT_INDEXED_LONG),
    Opcode(0x98, 'tya', AddressMode.IMPLIED),
    Opcode(0x99, 'sta', AddressMode.ABSOLUTE_INDEXED_Y),
    Opcode(0x9A, 'txs', AddressMode.IMPLIED),
    Opcode(0x9B, 'txy', AddressMode.IMPLIED),
    Opcode(0x9C, 'stz', AddressMode.ABSOLUTE),
    Opcode(0x9D, 'sta', AddressMode.ABSOLUTE_INDEXED_X),
    Opcode(0x9E, 'stz', AddressMode.ABSOLUTE_INDEXED_X),
    Opcode(0x9F, 'sta', AddressMode.ABSOLUTE_INDEXED_LONG),
    Opcode(0xA0, 'ldy', AddressMode.IMMEDIATE_X),
    Opcode(0xA1, 'lda', AddressMode.DIRECT_PAGE_INDEXED_INDIRECT),
    Opcode(0xA2, 'ldx', AddressMode.IMMEDIATE_X),
    Opcode(0xA3, 'lda', AddressMode.STACK_RELATIVE),
    Opcode(0xA4, 'ldy', AddressMode.DIRECT_PAGE),
    Opcode(0xA5, 'lda', AddressMode.DIRECT_PAGE),
    Opcode(0xA6, 'ldx', AddressMode.DIRECT_PAGE),
    Opcode(0xA7, 'lda', AddressMode.DIRECT_PAGE_INDIRECT_LONG),
    Opcode(0xA8, 'tay', AddressMode.IMPLIED),
    Opcode(0xA9, 'lda', AddressMode.IMMEDIATE_M),
    Opcode(0xAA, 'tax', AddressMode.IMPLIED),
    Opcode(0xAB, 'plb', AddressMode.IMPLIED),
    Opcode(0xAC, 'ldy', AddressMode.ABSOLUTE),
    Opcode(0xAD, 'lda', AddressMode.ABSOLUTE),
    Opcode(0xAE, 'ldx', AddressMode.ABSOLUTE),
    Opcode(0xAF, 'lda', AddressMode.ABSOLUTE_LONG),
    Opcode(0xB0, 'bcs', AddressMode.RELATIVE),
    Opcode(0xB1, 'lda', AddressMode.DIRECT_PAGE_INDIRECT_INDEXED),
    Opcode(0xB2, 'lda', AddressMode.DIRECT_PAGE_INDIRECT),
    Opcode(0xB3, 'lda', AddressMode.STACK_RELATIVE_INDIRECT_INDEXED),
    Opcode(0xB4, 'ldy', AddressMode.DIRECT_PAGE_INDEXED_X),
    Opcode(0xB5, 'lda', AddressMode.DIRECT_PAGE_INDEXED_X),
    Opcode(0xB6, 'ldx', AddressMode.DIRECT_PAGE_INDEXED_Y),
    Opcode(0xB7, 'lda', AddressMode.DIRECT_PAGE_INDIRECT_INDEXED_LONG),
    Opcode(0xB8, 'clv', AddressMode.IMPLIED),
    Opcode(0xB9, 'lda', AddressMode.ABSOLUTE_INDEXED_Y),
    Opcode(0xBA, 'tsx', AddressMode.IMPLIED),
    Opcode(0xBB, 'tyx', AddressMode.IMPLIED),
    Opcode(0xBC, 'ldy', AddressMode.ABSOLUTE_INDEXED_X),
    Opcode(0xBD, 'lda', AddressMode.ABSOLUTE_INDEXED_X),
    Opcode(0xBE, 'ldx', AddressMode.ABSOLUTE_INDEXED_Y),
    Opcode(0xBF, 'lda', AddressMode.ABSOLUTE_INDEXED_LONG),
    Opcode(0xC0, 'cpy', AddressMode.IMMEDIATE_X),
    Opcode(0xC1, 'cmp', AddressMode.DIRECT_PAGE_INDEXED_INDIRECT),
    Opcode(0xC2, 'rep', AddressMode.IMMEDIATE_8),
    Opcode(0xC3, 'cmp', AddressMode.STACK_RELATIVE),
    Opcode(0xC4, 'cpy', AddressMode.DIRECT_PAGE),
    Opcode(0xC5, 'cmp', AddressMode.DIRECT_PAGE),
    Opcode(0xC6, 'dec', AddressMode.DIRECT_PAGE),
    Opcode(0xC7, 'cmp', AddressMode.DIRECT_PAGE_INDIRECT_LONG),
    Opcode(0xC8, 'iny', AddressMode.IMPLIED),
    Opcode(0xC9, 'cmp', AddressMode.IMMEDIATE_M),
    Opcode(0xCA, 'dex', AddressMode.IMPLIED),
    Opcode(0xCB, 'wai', AddressMode.IMPLIED),
    Opcode(0xCC, 'cpy', AddressMode.ABSOLUTE),
    Opcode(0xCD, 'cmp', AddressMode.ABSOLUTE),
    Opcode(0xCE, 'dec', AddressMode.ABSOLUTE),
    Opcode(0xCF, 'cmp', AddressMode.ABSOLUTE_LONG),
    Opcode(0xD0, 'bne', AddressMode.RELATIVE),
    Opcode(0xD1, 'cmp', AddressMode.DIRECT_PAGE_INDIRECT_INDEXED),
    Opcode(0xD2, 'cmp', AddressMode.DIRECT_PAGE_INDIRECT),
    Opcode(0xD3, 'cmp', AddressMode.DIRECT_PAGE_INDIRECT),
    Opcode(0xD4, 'pei', AddressMode.PEI_DIRECT_PAGE_INDIRECT),
    Opcode(0xD5, 'cmp', AddressMode.DIRECT_PAGE_INDEXED_X),
    Opcode(0xD6, 'dec', AddressMode.DIRECT_PAGE_INDEXED_X),
    Opcode(0xD7, 'cmp', AddressMode.DIRECT_PAGE_INDIRECT_INDEXED_LONG),
    Opcode(0xD8, 'cld', AddressMode.IMPLIED),
    Opcode(0xD9, 'cmp', AddressMode.ABSOLUTE_INDEXED_Y),
    Opcode(0xDA, 'phx', AddressMode.IMPLIED),
    Opcode(0xDB, 'stp', AddressMode.IMPLIED),
    Opcode(0xDC, 'jml', AddressMode.ABSOLUTE_INDIRECT_LONG),
    Opcode(0xDD, 'cmp', AddressMode.ABSOLUTE_INDEXED_X),
    Opcode(0xDE, 'dec', AddressMode.ABSOLUTE_INDEXED_X),
    Opcode(0xDF, 'cmp', AddressMode.ABSOLUTE_INDEXED_LONG),
    Opcode(0xE0, 'cpx', AddressMode.IMMEDIATE_X),
    Opcode(0xE1, 'sbc', AddressMode.DIRECT_PAGE_INDEXED_INDIRECT),
    Opcode(0xE2, 'sep', AddressMode.IMMEDIATE_8),
    Opcode(0xE3, 'sbc', AddressMode.STACK_RELATIVE),
    Opcode(0xE4, 'cpx', AddressMode.DIRECT_PAGE),
    Opcode(0xE5, 'sbc', AddressMode.DIRECT_PAGE),
    Opcode(0xE6, 'inc', AddressMode.DIRECT_PAGE),
    Opcode(0xE7, 'sbc', AddressMode.DIRECT_PAGE_INDIRECT_LONG),
    Opcode(0xE8, 'inx', AddressMode.IMPLIED),
    Opcode(0xE9, 'sbc', AddressMode.IMMEDIATE_M),
    Opcode(0xEA, 'nop', AddressMode.IMPLIED),
    Opcode(0xEB, 'xba', AddressMode.IMPLIED),
    Opcode(0xEC, 'cpx', AddressMode.ABSOLUTE),
    Opcode(0xED, 'sbc', AddressMode.ABSOLUTE),
    Opcode(0xEE, 'inc', AddressMode.ABSOLUTE),
    Opcode(0xEF, 'sbc', AddressMode.ABSOLUTE_LONG),
    Opcode(0xF0, 'beq', AddressMode.RELATIVE),
    Opcode(0xF1, 'sbc', AddressMode.DIRECT_PAGE_INDIRECT_INDEXED),
    Opcode(0xF2, 'sbc', AddressMode.DIRECT_PAGE_INDIRECT),
    Opcode(0xF3, 'sbc', AddressMode.STACK_RELATIVE_INDIRECT_INDEXED),
    Opcode(0xF4, 'pea', AddressMode.PEA),
    Opcode(0xF5, 'sbc', AddressMode.DIRECT_PAGE_INDEXED_X),
    Opcode(0xF6, 'inc', AddressMode.DIRECT_PAGE_INDEXED_X),
    Opcode(0xF7, 'sbc', AddressMode.DIRECT_PAGE_INDIRECT_INDEXED_LONG),
    Opcode(0xF8, 'sed', AddressMode.IMPLIED),
    Opcode(0xF9, 'sbc', AddressMode.ABSOLUTE_INDEXED_Y),
    Opcode(0xFA, 'plx', AddressMode.IMPLIED),
    Opcode(0xFB, 'xce', AddressMode.IMPLIED),
    Opcode(0xFC, 'jsr', AddressMode.ABSOLUTE_INDEXED_INDIRECT),
    Opcode(0xFD, 'sbc', AddressMode.ABSOLUTE_INDEXED_X),
    Opcode(0xFE, 'inc', AddressMode.ABSOLUTE_INDEXED_X),
    Opcode(0xFF, 'sbc', AddressMode.ABSOLUTE_INDEXED_LONG),
)


size_table = [
    1,     # IMPLIED
    None,  # IMMEDIATE_M
    None,  # IMMEDIATE_X
    2,     # IMMEDIATE_8
    2,     # RELATIVE
    3,     # RELATIVE_LONG
    2,     # DIRECT_PAGE
    2,     # DIRECT_PAGE_INDEXED_X
    2,     # DIRECT_PAGE_INDEXED_Y
    2,     # DIRECT_PAGE_INDIRECT
    2,     # DIRECT_PAGE_INDEXED_INDIRECT
    2,     # DIRECT_PAGE_INDIRECT_INDEXED
    2,     # DIRECT_PAGE_INDIRECT_LONG
    2,     # DIRECT_PAGE_INDIRECT_INDEXED_LONG
    3,     # ABSOLUTE
    3,     # ABSOLUTE_INDEXED_X
    3,     # ABSOLUTE_INDEXED_Y
    4,     # ABSOLUTE_LONG
    4,     # ABSOLUTE_INDEXED_LONG
    2,     # STACK_RELATIVE
    2,     # STACK_RELATIVE_INDIRECT_INDEXED
    3,     # ABSOLUTE_INDIRECT
    3,     # ABSOLUTE_INDIRECT_LONG
    3,     # ABSOLUTE_INDEXED_INDIRECT
    1,     # IMPLIED_ACCUMULATOR
    3,     # MOVE
    3,     # PEA
    2,     # PEI_DIRECT_PAGE_INDIRECT
]
